[server]
host = "127.0.0.1"
port = 3000

[database]
url = "postgres://localhost/opengames_dev"
auto_create = true

[logging]
level = "debug"
format = "pretty"

[[logging.filter_modules]]
target = "og_api"
level = "info"

[[logging.filter_modules]]
target = "og_service"
level = "debug"

[[logging.filter_modules]]
target = "og_infra"
level = "info"
